"""add rejection reason to hotel owner applications

Revision ID: 0429a85c9075
Revises: 401656892567
Create Date: 2026-08-11 22:36:38.755785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0429a85c9075'
down_revision: Union[str, Sequence[str], None] = '401656892567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_owner_applications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_owner_applications', 'rejection_reason')
    # ### end Alembic commands ###
