"""add image column to hotels

Revision ID: 10ced52183f9
Revises: b0a015825cd5
Create Date: 2026-07-22 18:40:05.075580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ced52183f9'
down_revision: Union[str, Sequence[str], None] = 'b0a015825cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "hotels",
        sa.Column(
            "image",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute("""
        UPDATE hotels
        SET image = 'default.jpg'
        WHERE image IS NULL
    """)

    op.alter_column(
        "hotels",
        "image",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'image')
    # ### end Alembic commands ###
