"""create hotel owner applications table

Revision ID: 401656892567
Revises: f97091f5e6f9
Create Date: 2026-08-11 12:03:56.169162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401656892567'
down_revision: Union[str, Sequence[str], None] = 'f97091f5e6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_owner_applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=150), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('trade_license_number', sa.String(length=100), nullable=False),
    sa.Column('hotel_description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('trade_license_document', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_owner_applications_id'), 'hotel_owner_applications', ['id'], unique=False)
    op.create_index(op.f('ix_hotel_owner_applications_user_id'), 'hotel_owner_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_owner_applications_user_id'), table_name='hotel_owner_applications')
    op.drop_index(op.f('ix_hotel_owner_applications_id'), table_name='hotel_owner_applications')
    op.drop_table('hotel_owner_applications')
    # ### end Alembic commands ###
