"""associate hotels with destinations

Revision ID: a0bd964377c7
Revises: 59a5d16c5679
Create Date: 2026-07-21 15:50:45.529912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bd964377c7'
down_revision: Union[str, Sequence[str], None] = '59a5d16c5679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('destination_id', sa.Integer(), nullable=False))
    op.create_foreign_key("fk_hotels_destination_id", 'hotels', 'destinations', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_hotels_destination_id", 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'destination_id')
    # ### end Alembic commands ###
