"""add image column to destinations

Revision ID: b0a015825cd5
Revises: 490df51f5e99
Create Date: 2026-07-22 18:08:12.499958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a015825cd5'
down_revision: Union[str, Sequence[str], None] = '490df51f5e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable
    op.add_column(
        "destinations",
        sa.Column(
            "image",
            sa.String(length=255),
            nullable=True,
        ),
    )

    # Step 2: Give existing rows a placeholder value
    op.execute(
        """
        UPDATE destinations
        SET image = 'default.jpg'
        WHERE image IS NULL
        """
    )

    # Step 3: Make the column NOT NULL
    op.alter_column(
        "destinations",
        "image",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'image')
    # ### end Alembic commands ###
